services:
  traefik:
    image: traefik:latest
    restart: unless-stopped
    network_mode: host
    ports:
      - "80:80"
    command:
      - --api.dashboard=true
      - --api.insecure=false
      - --log.level=DEBUG
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  frontend:
    image: ghcr.io/ironnicko/tandemsync/frontend:latest
    restart: always
    expose:
      - "3000"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.frontend.rule=Host(`ts.nikhilivannan.live`)"
      - traefik.http.routers.frontend.entrypoints=web
      - traefik.http.services.frontend.loadbalancer.server.port=3000
    env_file:
      - ./.env

  backend:
    image: ghcr.io/ironnicko/tandemsync/backend:latest
    build:
        context: ./Backend
        dockerfile: Dockerfile
    restart: always
    expose:
      - "8000"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.backend.rule=Host(`ts.nikhilivannan.live`) && PathPrefix(`/api/v1`)"
      - traefik.http.routers.backend.entrypoints=web
      - traefik.http.services.backend.loadbalancer.server.port=8000
    env_file:
      - ./.env
    depends_on:
      - mongodb
      - dragonfly

  authserver:
    image: ghcr.io/ironnicko/tandemsync/authserver:latest
    build:
        context: ./AuthServer
        dockerfile: Dockerfile
    restart: always
    expose:
      - "8001"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.authserver.rule=Host(`ts.nikhilivannan.live`) && PathPrefix(`/api/auth`)"
      - traefik.http.routers.authserver.entrypoints=web
      - traefik.http.services.authserver.loadbalancer.server.port=8001
    env_file:
      - ./.env
    depends_on:
      - mongodb
      - dragonfly

  socket:
    image: ghcr.io/ironnicko/tandemsync/socket:latest
    build:
        context: ./SocketServer
        dockerfile: Dockerfile
    restart: always
    expose:
      - "3001"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.socket.rule=Host(`ts.nikhilivannan.live`) && PathPrefix(`/wss`)"
      - traefik.http.routers.socket.entrypoints=web
      - traefik.http.services.socket.loadbalancer.server.port=3001
    env_file:
      - ./.env
    depends_on:
      - dragonfly

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    restart: unless-stopped
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - ./dragonfly_data:/data

  redisinsight:
    image: redis/redisinsight
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - ./redisinsight_data:/db
    depends_on:
      - dragonfly

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_BASICAUTH_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_BASICAUTH_PASSWORD}
    depends_on:
      - mongodb
