// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Mutation struct {
}

type PushSubscriptionInput struct {
	DeviceID       string                     `json:"deviceId"`
	Endpoint       string                     `json:"endpoint"`
	Keys           *PushSubscriptionKeysInput `json:"keys"`
	ExpirationTime *string                    `json:"expirationTime,omitempty"`
}

type PushSubscriptionKeysInput struct {
	P256dh string `json:"p256dh"`
	Auth   string `json:"auth"`
}

type Query struct {
}

type UpdateUserInput struct {
	PushSubscription  *PushSubscriptionInput `json:"pushSubscription,omitempty"`
	ClearSubscription *bool                  `json:"clearSubscription,omitempty"`
}
